### ISSUE TITLE
Font references stored across frames

### ISSUE THREAD

**Issue by cschol** [djpeterso23662/MrLumps#15]
It looks like font references are stored across frames. This will crash the Rack VST.

```
src/SEQEuclid.cpp
394-    std::shared_ptr<Font> font;
395-
396-    SEQEuclidDisplayWidget() {
397:            font = APP->window->loadFont(asset::plugin(pluginInstance, "res/Segment7Standard.ttf"));
398-    }
399-
400-    void draw(const DrawArgs &args) override {
```

See [migration manual](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames) for more information on how to fix this.

**Comment by djpeterso23662** [comment]
Thanks for your review, @cschol, I really appreciate your time!  I removed font references stored across frames in 479658080d796a48b8993912cf2ed0fc534c3631.
